version: 0.0
os: linux
files:
  - source: / # CodeDeploy에 전달해 준 파일 중 destination에 이동시킬 대상을 지정, / 면 모든 파일
    destination: /home/ec2-user/app/ # source 에서 파일을 받을 위치 지정
    overwrite: yes # 기존 파일이 있다면, 덮어쓸 것인지 여부
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root