openapi: 3.0.1
info:
  title: 현지야
  description: 현지야 서버 Application API Document
  contact:
    email: dnxprbs@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://test.traveler.heylocal.com/
  - url: https://traveler.heylocal.com/
tags:
  - name: signin
    description: 로그인
  - name: signup
    description: 회원가입
  - name: user
    description: 사용자 정보
  - name: search
    description: 검색
  - name: post
    description: 포스트
  - name: manager
    description: 매니저
  - name: order
    description: 매칭 요청
  - name: ordersheet
    description: 여행 의뢰서
  - name: travel
    description: 여행
  - name: chat
    description: 채팅
  - name: policy
    description: 정책
paths:
  /signin:
    post:
      tags:
        - signin
      summary: 로그인
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /signup:
    post:
      tags:
        - signup
      summary: 회원가입
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /signup/id:
    get:
      tags:
        - signup
      summary: 아이디 중복 확인
      parameters:
        - name: id
          in: query
          description: 확인할 아이디
          required: true
          schema:
            type: string
      responses:
        405:
          description: Invalid input
          content: {}
  /signup/phone-num:
    get:
      tags:
        - signup
      summary: 전화번호 중복 확인 및 매니저로 등록되어 있는지 확인
      parameters:
        - name: phoneNumber
          in: query
          description: 확인할 전화번호 (- 제외)
          required: true
          schema:
            type: string
      responses:
        405:
          description: Invalid input
          content: {}
  /search/managers:
    get:
      tags:
        - search
      summary: 매니저 검색
      description: 지역 정보 및 테마로 매니저 검색, 모든 쿼리 파라미터에 입력된 정보가 없다면 4xx 오류 발생
      parameters:
        - name: state
          in: query
          description: 시/도
          schema:
            type: string
        - name: city
          in: query
          description: 시
          schema:
            type: string
        - name: themeId
          in: query
          description: 테마 id
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /search/random-managers:
    get:
      tags:
        - search
      summary: 랜덤 매니저 조회
      parameters:
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /search/popular-city:
    get:
      tags:
        - search
      summary: 현재 가장 인기있는 여행 도시 조회
      parameters:
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /search/theme:
    get:
      tags:
        - search
      summary: 워드로 테마 조회
      description: 테마 추가일 내림차순으로 응답
      parameters:
        - name: themeName
          in: query
          description: 검색할 테마 이름 키워드 (공란가능)
          schema:
            type: string
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /user/notifications:
    get:
      tags:
        - user
      summary: 사용자 푸쉬 알림 리스트 조회
      description: 로그인한 사용자가 받은 모든 푸쉬 알림 리스트 조회
      responses:
        405:
          description: Invalid input
          content: {}
  /user/profile:
    get:
      tags:
        - user
      summary: 사용자 프로필 사진, 닉네임 조회
      description: 로그인한 사용자의 프로필 사진과 닉네임 조회
      responses:
        405:
          description: Invalid input
          content: {}
    patch:
      tags:
        - user
      summary: 사용자 프로필 사진, 닉네임 수정
      description: 로그인한 사용자 프로필 사진, 닉네임 수정
      requestBody:
        description: 수정할 닉네임 or 수정할 사진
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /user/manager-reviews:
    get:
      tags:
        - user
      summary: 사용자가 남긴 매니저 평가 리스트 조회
      description: 로그인한 사용자가 남긴 매니저 평가 리스트 조회
      parameters:
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /user/visit-reviews:
    get:
      tags:
        - user
      summary: 사용자가 남긴 방문 리뷰 리스트 조회
      description: 로그인한 사용자가 남긴 방문 리뷰 리스트 조회
      parameters:
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /user/payment:
    get:
      tags:
        - user
      summary: 사용자의 결제 내역과 남은 포인트 조회
      description: 로그인한 사용자의 결제 내역과 남은 포인트 조회
      parameters:
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /user/withdrawal:
    post:
      tags:
        - user
      summary: 회원탈퇴
      responses:
        405:
          description: Invalid input
          content: {}
  /posts:
    get:
      tags:
        - post
      summary: 테마 관련 포스트 리스트 조회
      parameters:
        - name: themeid
          in: query
          description: 테마 id
          required: true
          schema:
            type: integer
        - name: onlysenior
          in: query
          description: '시니어 매니저의 포스트만 조회 옵션: true/false'
          required: true
          schema:
            type: boolean
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /posts/{postId}:
    get:
      tags:
        - post
      summary: 포스트 상세 조회
      parameters:
        - name: postId
          in: path
          description: 포스트 id
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /posts/{postId}/visit-reviews:
    get:
      tags:
        - post
      summary: 해당 포스트에 관련된 방문 리뷰 리스트 조회
      parameters:
        - name: postId
          in: path
          description: 포스트 id
          required: true
          schema:
            type: integer
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
    post:
      tags:
        - post
      summary: 해당 포스트에 방문 리뷰 등록
      parameters:
        - name: postId
          in: path
          description: 포스트 id
          required: true
          schema:
            type: integer
      requestBody:
        description: 방문 리뷰 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /posts/{postId}/visit-reviews/{visitReviewId}:
    delete:
      tags:
        - post
      summary: 해당 포스트의 자신의 방문 리뷰 삭제
      parameters:
        - name: postId
          in: path
          description: 포스트 id
          required: true
          schema:
            type: integer
        - name: visitReviewId
          in: path
          description: 삭제할 방문리뷰 id
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /managers/{managerId}/profile:
    get:
      tags:
        - manager
      summary: 해당 매니저의 프로필 조회
      parameters:
        - name: managerId
          in: path
          description: 매니저 id
          required: true
          schema:
            type: integer
        - name: simple
          in: query
          description: '간단한(상단 영역) 프로필 정보만 조회: true/false'
          required: true
          schema:
            type: boolean
      responses:
        405:
          description: Invalid input
          content: {}
  /managers/{managerId}/reviews:
    post:
      tags:
        - manager
      summary: 해당 매니저에게 매니저 리뷰 등록
      parameters:
        - name: managerId
          in: path
          description: 매니저 id
          required: true
          schema:
            type: integer
      requestBody:
        description: 매니저 리뷰 내용 + 리뷰할 여행 id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /managers/{managerId}/notes:
    get:
      tags:
        - manager
      summary: 해당 매니저의 꿀팁노트 리스트 조회
      parameters:
        - name: managerId
          in: path
          description: 매니저 id
          required: true
          schema:
            type: integer
        - name: page
          in: query
          description: 조회할 페이지
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /managers/{managerId}/notes/{noteId}:
    get:
      tags:
        - manager
      summary: 해당 매니저의 꿀팁노트 상세 조회
      parameters:
        - name: managerId
          in: path
          description: 매니저 id
          required: true
          schema:
            type: integer
        - name: noteId
          in: path
          description: 조회할 꿀팁노트 id
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /orders/request:
    post:
      tags:
        - order
      summary: 해당 매니저에게 특정 의뢰서로 매칭 요청
      requestBody:
        description: 매칭 요청할 매니저 id / 매칭 요청할 의뢰서 id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /orders/statuses:
    get:
      tags:
        - order
      summary: 내 매칭 요청 현황 리스트 조회
      parameters:
        - name: orderSheetId
          in: query
          description: 매칭 현황을 확인할 여행 의뢰서 id
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: 'traveler:내가 보낸 매칭 요청, manager: 받은 매칭 요청'
          required: true
          schema:
            type: string
      responses:
        405:
          description: Invalid input
          content: {}
  /ordersheets:
    get:
      tags:
        - ordersheet
      summary: 여행 의뢰서 리스트 조회
      parameters:
        - name: status
          in: query
          description: '현재 의뢰서: now, 지난 의뢰서: past'
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: 조회할 페이지 번호
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
    post:
      tags:
        - ordersheet
      summary: 여행 의뢰서 등록
      description: 의뢰비를 응답받는다.
      requestBody:
        description: 등록할 여행 의뢰서 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sample'
        required: true
      responses:
        405:
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
  /ordersheets/{orderSheetId}:
    get:
      tags:
        - ordersheet
      summary: 여행 의뢰서 상세 조회
      parameters:
        - name: orderSheetId
          in: path
          description: 조회할 여행 의뢰서 id
          required: true
          schema:
            type: string
      responses:
        405:
          description: Invalid input
          content: {}
  /travels:
    get:
      tags:
        - travel
      summary: 다가오는 여행, 진행 중인 여행, 지난 여행 리스트 조회
      parameters:
        - name: futureTravelPage
          in: query
          description: 조회할 페이지 번호 (다가오는 여행)
          required: true
          schema:
            type: integer
        - name: nowTravelPage
          in: query
          description: 조회할 페이지 번호 (진행중인 여행)
          required: true
          schema:
            type: integer
        - name: pastTravelPage
          in: query
          description: 조회할 페이지 번호 (지난 여행)
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /travels/{travelId}:
    get:
      tags:
        - travel
      summary: 여행 상세 조회
      parameters:
        - name: travelId
          in: path
          description: 조회할 여행 id
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /travels/{travelId}/schedules/{scheduleId}:
    post:
      tags:
        - travel
      summary: 스케줄표 확정
      parameters:
        - name: travelId
          in: path
          description: 조회할 여행 id
          required: true
          schema:
            type: integer
        - name: scheduleId
          in: path
          description: 확정할 스케줄표 id
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /chatrooms:
    get:
      tags:
        - chat
      summary: 채팅방 리스트 조회
      responses:
        405:
          description: Invalid input
          content: {}
  /chatrooms/{chatroomId}:
    get:
      tags:
        - chat
      summary: 채팅방 상세 조회
      parameters:
        - name: chatroomId
          in: path
          description: 조회할 채팅방 id
          required: true
          schema:
            type: integer
      responses:
        405:
          description: Invalid input
          content: {}
  /policies/price:
    get:
      tags:
        - policy
      summary: 가격 정책 정보 조회
      responses:
        405:
          description: Invalid input
          content: {}
components:
  schemas:
    Sample:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
          default: false
      xml:
        name: Order
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Category
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
      xml:
        name: User
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: Tag
    Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/Category'
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          xml:
            name: photoUrl
            wrapped: true
          items:
            type: string
        tags:
          type: array
          xml:
            name: tag
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
      xml:
        name: Pet
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
