/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.heylocal.traveler.controller.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-08-12T04:12:44.357Z[GMT]")
@RequestMapping("/chatrooms")
public interface ChatRoomsApi {

    @Operation(summary = "채팅방 상세 조회", description = "", tags={ "chat" })
    @GetMapping("/{chatroomId}")
    ResponseEntity<Void> chatRoomsChatroomIdGet(
        @Parameter(in = ParameterIn.PATH, description = "조회할 채팅방 id", required = true) @PathVariable long chatroomId);


    @Operation(summary = "채팅방 리스트 조회", description = "", tags={ "chat" })
    @GetMapping()
    ResponseEntity<Void> chatRoomsGet();

}

