/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.heylocal.traveler.controller.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-08-12T04:12:44.357Z[GMT]")
@RequestMapping("/travels")
public interface TravelsApi {

    @Operation(summary = "다가오는 여행, 진행 중인 여행, 지난 여행 리스트 조회", description = "", tags = {"Travels"})
    @GetMapping()
    ResponseEntity<Void> travelsGet(
        @Parameter(in = ParameterIn.QUERY, description = "조회할 페이지 번호 (다가오는 여행)", required = true) @RequestParam int futureTravelPage,
        @Parameter(in = ParameterIn.QUERY, description = "조회할 페이지 번호 (진행중인 여행)", required=true) @RequestParam int nowTravelPage,
        @Parameter(in = ParameterIn.QUERY, description = "조회할 페이지 번호 (지난 여행)", required = true) @RequestParam int pastTravelPage);


    @Operation(summary = "여행 상세 조회", description = "", tags = {"Travels"})
    @GetMapping("/{travelId}")
    ResponseEntity<Void> travelsTravelIdGet(
        @Parameter(in = ParameterIn.PATH, description = "조회할 여행 id", required = true) @PathVariable long travelId);


    @Operation(summary = "스케줄표 확정", description = "", tags = {"Travels"})
    @PostMapping("/{travelId}/schedules/{scheduleId}")
    ResponseEntity<Void> travelsTravelIdSchedulesScheduleIdPost(
        @Parameter(in = ParameterIn.PATH, description = "조회할 여행 id", required = true) @PathVariable long travelId,
        @Parameter(in = ParameterIn.PATH, description = "확정할 스케줄표 id", required = true) @PathVariable long scheduleId);

}

