/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.heylocal.traveler.controller.api;

import io.swagger.v3.oas.annotations.Operation;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-08-12T04:12:44.357Z[GMT]")
@RequestMapping("/travel-ons")
public interface TravelOnsApi {

    @Operation(summary = "여행On 리스트 조회", description = "", tags = {"TravelOns"})
    @GetMapping()
    ResponseEntity<Void> travelOnsGet();


    @Operation(summary = "여행On 상세 조회", description = "", tags = {"TravelOns"})
    @GetMapping(value = "/{travelOnId}")
    ResponseEntity<Void> travelOnDetailGet();


    @Operation(summary = "여행On 등록", description = "", tags = {"TravelOns"})
    @PostMapping(consumes = { "application/json" })
    ResponseEntity<Void> travelOnsPost();

}

